services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    volumes:
      - ./uptime-kuma-data:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
  database:
    image: mysql:9.1.0
    environment:
      - MYSQL_ROOT_PASSWORD=jaringan123
      - MYSQL_DATABASE=people
      - MYSQL_USER=people
      - MYSQL_PASSWORD=people
    ports:
      - 3306:3306
    volumes:
        - ./database:/docker-entrypoint-initdb.d
  prometheus:
    image: prom/prometheus:v3.0.0
    volumes:
      - ./prometheus-config:/etc/prometheus
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:latest
    ports:
      - 8000:3000