scrape_configs:
  - job_name: "uptime"
    scrape_interval: 30s
    scheme: http
    metrics_path: "/metrics"
    static_configs:
      - targets: ["uptime-kuma:3001"]
    basic_auth: # Only needed if authentication is enabled (default)
      username: tombo0
      password: 5246373056Aa
      